# NOTE: Colors are shown when their number of verbosity is enabled.
#       See help menu for more information. Not applicable to wall/path.
# Verbosity: 2 = Logic only, 3 = Style only, 4 = Logic and Style
#######################################################################
########################    MAZE ALGORITHMS    ########################
#######################################################################
[aldous_broder]
# color of the walls and unlinked cells
wall.color = 16
wall.character = "█"

# color of the paths (linked cells)
path.color = 34
path.character = "█"

# current cell being assessed for linking
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.frames_per_value = 1
working_cell.colors = [218]
working_cell.characters = []

# last grid cell that was linked into the maze
last_linked.verbosity = [3,4]
last_linked.layer = 1
last_linked.frames_per_value = 30
last_linked.colors = [82,46,40,34,28]
last_linked.characters = ["0","10","1"]

# neighbors invalid for linking (adjacent to the working cell)
invalid_neighbors.verbosity = [2,4]
invalid_neighbors.layer = 0
invalid_neighbors.frames_per_value = 1
invalid_neighbors.colors = [159]
invalid_neighbors.characters = []

# cells that are already linked into the maze and are being revisted
invalid_visited.verbosity = [3,4]
invalid_visited.layer = 0
invalid_visited.frames_per_value = 3
invalid_visited.colors = [34,28,22,22,22,28,34]
invalid_visited.characters = ["▇","▆","▅","▄","▅","▆","▇"]
#invalid_visited.colors = [34,28,22,28,34]
#invalid_visited.characters = ["▓","▒","░","▒","▓"]

###########################
###########################
[binary_tree]
# color of the walls and unlinked cells
wall.color = 240
wall.character = "█"

# color of the paths (linked cells)
path.color = 6
path.character = "█"

# current cell being assessed for linking
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.frames_per_value = 1
working_cell.colors = [218]
working_cell.characters = []

# cell last linked into the maze
last_linked.verbosity = [2,4]
last_linked.layer = 0
last_linked.frames_per_value = 1
last_linked.colors = [159]
last_linked.characters = []

# eighbors adjacent to the cell
neighbors.verbosity = [2,4]
neighbors.layer = 0
neighbors.frames_per_value = 1
neighbors.colors = [159]
neighbors.characters = []

###########################
###########################
[ellers]
#NOTE: Ellers algorithm relies on random colors for the cell groups which
#      limits configuration options. Path color may only be observed after
#      maze generation has completed.

# color of the walls and unlinked cells
wall.color = 240
wall.character = "█"

# color of the paths (linked cells)
path.color = 6
path.character = "█"

# groups of cells
group_to_random_color.verbosity = [2,3,4]
group_to_random_color.layer = 0
group_to_random_color.character = ""

###########################
###########################
[hunt_and_kill]
# color of the walls and unlinked cells
wall.color = 16
wall.character = "█"

# color of the paths (linked cells)
path.color = 34
path.character = "█"

# current cell being assessed for linking
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.frames_per_value = 1
working_cell.colors = [218]
working_cell.characters = []

# neighbors invalid for linking (adjacent to the working cell)
invalid_neighbors.verbosity = [2,4]
invalid_neighbors.layer = 0
invalid_neighbors.frames_per_value = 1
invalid_neighbors.colors = [88]
invalid_neighbors.characters = []

# last cell linked into the grid
last_linked.verbosity = [3,4]
last_linked.layer = 0
last_linked.frames_per_value = 2
last_linked.characters = []
last_linked.colors = [46, 47, 48, 49, 50]

# unlinked cells passed over while in the hunting state
hunt_cells.verbosity = [3,4]
hunt_cells.layer = 0
hunt_cells.frames_per_value = 1
hunt_cells.colors = [47, 48, 49, 50]
hunt_cells.characters = []


###########################
###########################
[kruskals_randomized]
#NOTE: Kruskal's Randomized algorithm relies on random colors for the cell groups which
#      limits configuration options. Path color may only be observed after
#      maze generation has completed.

# color of the walls and unlinked cells
wall.color = 240
wall.character = "█"

# color of the paths (linked cells)
path.color = 6
path.character = "█"

# groups of cells
group_random_color.verbosity = [2,3,4]
group_random_color.layer = 0
group_random_color.character = ""

###########################
###########################
[prims_simple]
# color of the walls and unlinked cells
wall.color = 240
wall.character = "█"

# color of the paths (linked cells)
path.color = 6
path.character = "█"

# current cell being assessed for linking
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.frames_per_value = 1
working_cell.colors = [218]
working_cell.characters = []

# cells on the edge of the linked area
edges.verbosity = [3,4]
edges.layer = 0
edges.frames_per_value = 10
edges.colors = [159]
edges.characters = []

# neighbors invalid for linking (adjacent to the working cell)
invalid_neighbors.verbosity = [2,4]
invalid_neighbors.layer = 0
invalid_neighbors.frames_per_value = 1
invalid_neighbors.colors = [52]
invalid_neighbors.characters = []

# last cell that was linked into the maze
last_linked.verbosity = [2,4]
last_linked.layer = 0
last_linked.frames_per_value = 10
last_linked.colors = [218]
last_linked.characters = []

###########################
###########################
[prims_weighted]
# color of the walls and unlinked cells
wall.color = 240
wall.character = "█"

# color of the paths (linked cells)
path.color = 6
path.character = "█"

# current cell being assessed for linking
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.frames_per_value = 1
working_cell.colors = [218]
working_cell.characters = []

# links encountered but not linked due to high cost
pending_weighted_links.verbosity = [3,4]
pending_weighted_links.layer = 0
pending_weighted_links.color = 79
pending_weighted_links.character = ""

# newly discovered links not linked due to high cost
new_weighted_links.verbosity = [3,4]
new_weighted_links.layer = 1
new_weighted_links.frames_per_value = 15
new_weighted_links.colors = [82,76,77,78]
new_weighted_links.characters = []

# cells adjacent to the workingcell that are not linked
unlinked_neighbors.verbosity = [2,4]
unlinked_neighbors.layer = 0
unlinked_neighbors.frames_per_value = 1
unlinked_neighbors.colors = [218]
unlinked_neighbors.characters = []

# cell last linked into the maze
last_linked.verbosity = [3,4]
last_linked.layer = 2
last_linked.frames_per_value = 1
last_linked.colors = [47, 48, 49, 50]
last_linked.characters = []

###########################
###########################
[recursive_backtracker]
# color of the walls and unlinked cells
wall.color = 16
wall.character = "█"

# color of the paths (linked cells)
path.color = 34
path.character = "█"

# current cell being assessed for linking
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.frames_per_value = 1
working_cell.colors = [218]
working_cell.characters = []

# path on the first pass, before backtracking
stack.verbosity = [3,4]
stack.layer = 0
stack.color = 22
stack.character = ""

# neighbors invalid for linking (adjacent to the working cell)
invalid_neighbors.verbosity = [2,4]
invalid_neighbors.layer=0
invalid_neighbors.frames_per_value = 1
invalid_neighbors.colors = [52]
invalid_neighbors.characters = []

# last cell that was linked into the maze
last_linked.verbosity = [2,4]
last_linked.layer = 0
last_linked.frames_per_value = 1
last_linked.colors = [218]
last_linked.characters = []

# cells as they are added to the stack
stack_added_cells.verbosity = [3,4]
stack_added_cells.layer = 0
stack_added_cells.frames_per_value = 3
stack_added_cells.colors = [82,46,40,34,28]
stack_added_cells.characters = []

# cells as they are removed from the stack
stack_removed_cells.verbosity = [3,4]
stack_removed_cells.layer = 1
stack_removed_cells.frames_per_value = 3
stack_removed_cells.colors = [82,46,40,34]
stack_removed_cells.characters = []

###########################
###########################
[side_winder]
# color of the walls and unlinked cells
wall.color = 240
wall.character = "█"

# color of the paths (linked cells)
path.color = 6
path.character = "█"

# cells in each run prior to making an upward link
run.verbosity = [2,4]
run.layer = 1
run.color = 218
run.character = ""

# current cell being assessed for linking
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.frames_per_value = 1
working_cell.colors = [218]
working_cell.characters = []

# last cell that was linked into the maze
last_linked.verbosity = [2,4]
last_linked.layer = 0
last_linked.frames_per_value = 10
last_linked.colors = [159]
last_linked.characters = []

###########################
###########################
[wilsons]
# color of the walls and unlinked cells
wall.color = 240
wall.character = "█"

# color of the paths (linked cells)
path.color = 6
path.character = "█"

# cell being targeted for the initial linked path
target.verbosity = [2,3,4]
target.layer = 0
target.color = 218
target.character = ""

# unlinked cells showing the walk searching for the maze
walk.verbosity = [2,3,4]
walk.layer = 0
walk.color = 49
walk.character = ""

# current cell being assessed for linking
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.frames_per_value = 1
working_cell.colors = [14]
working_cell.characters = []

# walks linked into the maze
new_linked_walks.verbosity = [3,4]
new_linked_walks.layer = 0
new_linked_walks.frames_per_value = 10
new_linked_walks.colors = [50, 87, 86, 50,44,37]
new_linked_walks.characters = []

# last cell linked into the walk
last_linked.verbosity = [3,4]
last_linked.layer = 1
last_linked.frames_per_value = 5
last_linked.colors = [56,62,68,74]
last_linked.characters = []

########################################################################
########################    Solve Algorithms    ########################
########################################################################
# NOTE: Path and Wall color cannot be set by Solve algorithms, must be set by the
#       maze algorithm responsible for the maze.
[breadth_first]

# current cell being assessed for neighbors in the path
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.color = 218
working_cell.character = ""

# color of cells on the outer edge of the search area
frontier.verbosity = [2,4]
frontier.layer = 0
frontier.color = 82
frontier.character = ""

# color of cells that have been visited
visited.verbosity = [3,4]
visited.layer = 0
visited.color = 172
visited.character = ""

# cells visited on the search path
# (color at index 0 is the start of the transition)
visited_animation.verbosity = [3,4]
visited_animation.layer = 1
visited_animation.frames_per_value = 10
visited_animation.colors = [46,40,34,28,22,16,22,28,22,16,94,172]
visited_animation.characters = ["█","█","█","█","█","█","01","01","01","01"]

# color of cell being targeted for the solution path
target.verbosity = [2,4]
target.layer = 0
target.color = 202
target.character = ""

# color of the solution path discovered
solution_path.verbosity = [2,3,4]
solution_path.layer = 1
solution_path.color = 46
solution_path.character = ""

# cells visited on the solution path
# (value at index 0 is the start of the transition)
solution_animation.verbosity = [3,4]
solution_animation.layer = 2
solution_animation.frames_per_value = 2
solution_animation.colors = [21,93,92,91,89,160,166,172,178,184,190,154,118]
solution_animation.characters = []
######################################################
######################################################
[breadth_first_early_exit]

# current cell being assessed for neighbors in the path
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.color = 218
working_cell.character = ""

# color of cells on the outer edge of the search area
frontier.verbosity = [2,4]
frontier.layer = 0
frontier.color = 82
frontier.character = ""

# color of cells that have been visited
visited.verbosity = [3,4]
visited.layer = 0
visited.color = 172
visited.character = ""

# cells visited on the search path
# (color at index 0 is the start of the transition)
visited_animation.verbosity = [3,4]
visited_animation.layer = 1
visited_animation.frames_per_value = 10
visited_animation.colors = [46,40,34,28,22,16,22,28,22,16,94,172]
visited_animation.characters = ["█","█","█","█","█","█","01","01","01","01"]

# color of cell being targeted for the solution path
target.verbosity = [2,4]
target.layer = 0
target.color = 202
target.character = ""

# color of the solution path discovered
solution_path.verbosity = [2,3,4]
solution_path.layer = 1
solution_path.color = 46
solution_path.character = ""

# cells visited on the solution path
# (value at index 0 is the start of the transition)
solution_animation.verbosity = [3,4]
solution_animation.layer = 2
solution_animation.frames_per_value = 2
solution_animation.colors = [21,93,92,91,89,160,166,172,178,184,190,154,118]
solution_animation.characters = []
######################################################
######################################################
[greedy_best_first]

# current cell being assessed for neighbors in the path
working_cell.verbosity = [2,4]
working_cell.layer = 0
working_cell.color = 218
working_cell.character = ""

# color of cells on the outer edge of the search area
frontier.verbosity = [2,4]
frontier.layer = 0
frontier.color = 82
frontier.character = ""

# color of cells that have been visited
visited.verbosity = [2,3,4]
visited.layer = 0
visited.color = 172
visited.character = ""

# cells visited on the search path
# (color at index 0 is the start of the transition)
visited_animation.verbosity = [3,4]
visited_animation.layer = 1
visited_animation.frames_per_value = 10
visited_animation.colors = [46,40,34,28,22,16,22,28,22,16,94,172]
visited_animation.characters = ["█","█","█","█","█","█","01","01","01","01"]

# color of cell being targeted for the solution path
target.verbosity = [2,4]
target.layer = 0
target.color = 202
target.character = ""

# color of the solution path discovered
solution_path.verbosity = [2,3,4]
solution_path.layer = 1
solution_path.color = 46
solution_path.character = ""

# cells visited on the solution path
# (value at index 0 is the start of the transition)
solution_animation.verbosity = [3,4]
solution_animation.layer = 2
solution_animation.frames_per_value = 2
solution_animation.colors = [21,93,92,91,89,160,166,172,178,184,190,154,118]
solution_animation.characters = []
######################################################
######################################################