# NOTE: Colors are shown when their category of verbosity is enabled.
#       See help menu for more information. Not applicable to wall/path.
# Verbosity: 2 = Logic only, 3 = Style only, 4 = Logic and Style
#######################################################################
########################    MAZE ALGORITHMS    ########################
#######################################################################
[aldous_broder]
# Verbosity - All: color of the walls and unlinked cells
wall = 240

# Verbosity - All: color of the paths (linked cells)
path = 6

# Verbosity - LOGIC: color of the current cell being assessed for linking
workingcell = 218

# Verbosity - STYLE: color of the last grid cell that was linked into the maze
lastlinked = 218

# Verbosity - LOGIC: color for neighbors invalid for linking (adjacent to the working cell)
invalidneighbors = 159

# Verbosity - STYLE: color for cells that are already linked into the maze and are being revisted
invalidvisited = 159

###########################
###########################
[binary_tree]
# Verbosity - All: color of the walls and unlinked cells
wall = 240

# Verbosity - All: color of the paths (linked cells)
path = 6

# Verbosity - LOGIC: color of the current cell being assessed for linking
workingcell = 218

# Verbosity - LOGIC: color for neighbors adjacent to the cell
neighbor = 159

###########################
###########################
[ellers]
#NOTE: Ellers algorithm relies on random colors for the cell groups which
#      limits configuration options. Path color may only be observed after
#      maze generation has completed.
# Verbosity - All: color of the walls and unlinked cells
wall = 240

# Verbosity - All: color of the paths (linked cells)
path = 6

###########################
###########################
[hunt_and_kill]
# Verbosity - All: color of the walls and unlinked cells
wall = 240

# Verbosity - All: color of the paths (linked cells)
path = 6

# Verbosity - LOGIC: color of the current cell being assessed for linking
workingcell = 218

# Verbosity - LOGIC: color of the last grid cell that was linked into the maze
lastlinked = 49

# Verbosity - LOGIC: color for neighbors invalid for linking (adjacent to the working cell)
invalidneighbors = 88

# Verbosity - STYLE: gradient trail beind the working cell as it travels forward
# (color at index 0 is the front color)
#   number of colored cells will be up to the length of this list
linktrail = [46, 47, 47, 48, 48, 48, 48, 49, 49, 49, 49, 50, 50]

# Verbosity - STYLE: color trail that follows the hunt position during the hunt phase
huntcells = 49

###########################
###########################
[kruskals_randomized]
#NOTE: Kruskal's Randomlized algorithm relies on random colors for the cell groups which
#      limits configuration options. Path color may only be observed after
#      maze generation has completed.
# Verbosity - All: color of the walls and unlinked cells
wall = 240
# Verbosity - All: color of the paths (linked cells)
path = 6

###########################
###########################
[prims_simple]
# Verbosity - All: color of the walls and unlinked cells
wall = 240

# Verbosity - All: color of the paths (linked cells)
path = 6

# Verbosity - LOGIC: color of the current cell being assessed for linking
workingcell = 218

# Verbosity - STYLE: color of cells on the edge of the linked area
edges = 159

# Verbosity - LOGIC: color for neighbors invalid for linking (adjacent to the working cell)
invalidneighbors = 52

# Verbosity - LOGIC: color of the last grid cell that was linked into the maze
lastlinked = 159

# Verbosity - STYLE: color of cells second to the edge of the maze
oldedges = 218

###########################
###########################
[prims_weighted]
# Verbosity - All: color of the walls and unlinked cells
wall = 240
# Verbosity - All: color of the paths (linked cells)
path = 6

# Verbosity - LOGIC: color of the current cell being assessed for linking
workingcell = 218

# Verbosity - STYLE: color of cells awaiting linking
links = 79

# Verbosity - LOGIC: color of cells adjacent to the workingcell that are not linked
unlinkedneighbors = 218

# Verbosity - STYLE: gradient trail showing recently linked cells
# (color at index 0 is the front color)
lastlinked = [47, 47, 48, 48, 48, 49, 49, 49, 49, 50, 50]

###########################
###########################
[recursive_backtracker]
# Verbosity - All: color of the walls and unlinked cells
wall = 16

# Verbosity - All: color of the paths (linked cells)
path = 34

# Verbosity - STYLE: color of the path on the first pass, before backtracking
stack = 22

# Verbosity - LOGIC: color of the current cell being assessed for linking
workingcell = 218

# Verbosity - LOGIC: color for neighbors invalid for linking (adjacent to the working cell)
invalidneighbors = 52

# Verbosity - LOGIC: color of the last grid cell that was linked into the maze
lastlinked = 218

# Verbosity - STYLE: gradient trail on the front of the stack as it travels forward
# (color at index 0 is the front color)
#   number of colored cells will be up to the length of this list
stacktrail = [82,46,40,34,28]

# Verbosity - STYLE: gradient trail off the end of the stack as it travels backward
# (color at index 0 is the front color)
#   number of colored cells will be up to the length of this list
backtracktrail = [82,46,40,34]

###########################
###########################
[sidewinder]
# Verbosity - All: color of the walls and unlinked cells
wall = 240

# Verbosity - All: color of the paths (linked cells)
path = 6

# Verbosity - LOGIC: color of cells in each run prior to making an upward link
run = 218

# Verbosity - LOGIC: color of the current cell being assessed for linking
workingcell = 218

# Verbosity - LOGIC: color of the last grid cell that was linked into the maze
lastlinked = 159

###########################
###########################
[wilsons]
# Verbosity - All: color of the walls and unlinked cells
wall = 240

# Verbosity - All: color of the paths (linked cells)
path = 6

# Verbosity - LOGIC: color of the cell being targeted for the initial linked path
target = 218

# Verbosity - LOGIC: color of the path while drawing new linked paths
walk = 49

# Verbosity - LOGIC: color of the current cell being assessed for linking
workingcell = 14

# Verbosity - STYLE: transition colors undergone by new links
linktransition = [50, 87, 86, 50,44,37]

########################################################################
########################    Solve Algorithms    ########################
########################################################################
# NOTE: Path and Wall color cannot be set by Solve algorithms, must be set by the
#       maze algorithm responsible for the maze.
[breadthfirst]
# Verbosity - LOGIC: color of cells on the outer edge of the search area
frontier = 82

# Verbosity - STYLE: color of cells that have been visited
visited = 172

# Verbosity - LOGIC: color of cell being targeted for the solution path
target = 202

# Verbosity - LOGIC: current cell being assessed for neighbors in the path
workingcell = 218

# Verbosity - LOGIC: color of the solution path discovered
solutionpath = 46

# Verbosity - STYLE: transitioning colors of the search path
# (color at index 0 is the start of the transition)
pathtransition = [46,40,34,28,22,16,16,16,16,16,94,172]

# Verbosity - STYLE: transitioning colors of the solution path
# (color at index 0 is the start of the transition)
solutiontransition = [21,93,92,91,89,160,166,172,178,184,190,154,118]
